apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: latency-probe
  labels:
    app: latency-probe-nodeport
spec:
  selector:
    matchLabels:
      app: latency-probe
  template:
    metadata:
      labels:
        app: latency-probe
    spec:
      hostNetwork: true
      containers:
      - name: latency-probe
        image: 192.168.0.112:32000/latency-probe:latest
        ports:
        - containerPort: 8082
      restartPolicy: Always
