apiVersion: v1
kind: Pod
metadata:
  name: wasm-inference-docker
  labels:
    app: wasm-inference
spec:
  nodeSelector:
    kubernetes.io/hostname: gustavojardim
  restartPolicy: Always
  containers:
    - name: server
      image: 192.168.0.112:32000/wasm-inference-docker:latest
      ports:
        - containerPort: 8081
  volumes:
    - name: wasm
      hostPath:
        path: /opt/wasm
        type: DirectoryOrCreate