apiVersion: v1
kind: Pod
metadata:
  name: wasm-inference-docker
  labels:
    app: wasm-inference
spec:
  restartPolicy: Always
  containers:
    - name: server
      image: 127.0.0.1:32000/wasm-inference-docker:latest
      ports:
        - containerPort: 8081
  volumes:
    - name: wasm
      hostPath:
        path: /opt/wasm
        type: DirectoryOrCreate