apiVersion: v1
kind: Service
metadata:
  name: wasm-server
spec:
  type: NodePort
  selector:
    app: wasm-server
  ports:
    - name: ws
      port: 9001
      targetPort: 9001
      nodePort: 30001