apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: qos-monitor
  labels:
    app: qos-monitor
spec:
  selector:
    matchLabels:
      app: qos-monitor
  template:
    metadata:
      labels:
        app: qos-monitor
      annotations:
        module.wasm.image/variant: "compat"
    spec:
      runtimeClassName: wasmtime
      hostNetwork: true
      containers:
        - name: qos-monitor
          image: 192.168.0.112:32000/wasm-inference:latest
          imagePullPolicy: Always
          command: ["app.wasm", "device", "--cpu", "--udp"]
          ports:
            - containerPort: 8081
              name: udp
              protocol: UDP